name:                data-crunch
version:             0.1.0.0
github:              "entro-pi/data-crunch"
license:             BSD3
author:              "Taylor Belland"
maintainer:          "taylorbelland@gmail.com"
copyright:           "Taylor Belland"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/entro-pi/data-crunch#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  data-crunch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-crunch

tests:
  data-crunch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-crunch
